import "dotenv/config";

import { Worker, Job } from "bullmq";
import Redis from "ioredis";
import { runSupervisorStream } from "./agents/supervisor";
import { GENERATION_QUEUE_NAME } from "./lib/queue";
import { recordArticleRead, deductUserTokens } from "./lib/db";
import { pipelineLogger } from "./lib/observability";

const redisConnection = new Redis(
  process.env.REDIS_URL || "redis://localhost:6379",
  {
    maxRetriesPerRequest: null,
  },
);

// Dedicated Redis connection for Pub/Sub subscriptions (required)
const redisSub = new Redis(
  process.env.REDIS_URL || "redis://localhost:6379"
);

// Map to keep track of active job abort controllers for cancellation dispatching
const activeAbortControllers = new Map<string, AbortController>();

redisSub.on("message", (channel, message) => {
  if (channel.startsWith("job-cancel:")) {
    const jobId = channel.split(":")[1];
    const controller = activeAbortControllers.get(jobId);
    if (controller) {
      console.log(`🛑 [Worker] Cancellation signal received for job ${jobId}. Aborting...`);
      controller.abort();
    }
  }
});

console.log("👷 [Worker] Starting LangGraph Worker Node...");

const worker = new Worker(
  GENERATION_QUEUE_NAME,
  async (job: Job) => {
    const { userId, interests, hint, topic } = job.data;
    const jobId = job.id;
    if (!jobId) {
      throw new Error("Job ID was not generated by BullMQ");
    }

    console.log(`⚙️ [Worker] Processing job ${jobId} for user ${userId}`);

    const controller = new AbortController();
    activeAbortControllers.set(jobId, controller);

    const cancelChannel = `job-cancel:${jobId}`;
    await redisSub.subscribe(cancelChannel);

    const startTime = new Date().toISOString();
    let resultState: any = null;
    let errorMsg: string | undefined;

    try {
      resultState = await runSupervisorStream(
        interests,
        userId,
        controller.signal,
        async (event) => {
          await job.updateProgress(event);
        },
        undefined,
        hint,
        topic,
      );

      if (!resultState.currentTopic || !resultState.article) {
        throw new Error("Pipeline completed but failed to produce any content.");
      }

      if (resultState.articleId) {
        await recordArticleRead(userId, resultState.articleId);
      }

      const nodes = resultState.nodeMetrics || [];
      const totalTokens = nodes.reduce(
        (acc: number, n: any) =>
          acc + (n.inputTokens || 0) + (n.outputTokens || 0),
        0,
      );
      if (totalTokens > 0) {
        await deductUserTokens(userId, totalTokens).catch((e: any) =>
          console.error(`⚠️ [Token Deduction Error]:`, e),
        );
      }

      const obsNode = nodes.find((n: any) => n.nodeName === "observability");
      const editNode = nodes.find((n: any) => n.nodeName === "editor");

      // Observability Logging
      await pipelineLogger.logRun({
        userId,
        topic: resultState.currentTopic?.title,
        domain: resultState.currentTopic?.domain,
        startTime,
        nodes,
        tavilySearchCount: nodes.reduce(
          (acc: number, n: any) => acc + (n.tavilyCount || 0),
          0,
        ),
        totalCostEstimate: 0,
        status: "success",
        researchFactCount: resultState.researchFactCount,
        briefFactCount: resultState.briefFactCount,
        outlineSectionCount: resultState.outlineSectionCount,
        articleWordCount: resultState.articleWordCount,
        researchFactsUsed: resultState.researchFactsUsed,
        mustIncludeFacts: obsNode?.mustIncludeFacts,
        mustIncludeFactsUsed: obsNode?.mustIncludeFactsUsed,
        outlineTargetWords: obsNode?.outlineTargetWords,
        actualArticleWords: obsNode?.actualArticleWords,
        factConsistency: obsNode?.factConsistency,
        hookStrength: obsNode?.hookStrength,
        narrativeFlow: obsNode?.narrativeFlow,
        curiosityFactor: obsNode?.curiosityFactor,
        sectionBalance: obsNode?.sectionBalance,
        conclusionQuality: obsNode?.conclusionQuality,
        unsupportedClaims: obsNode?.unsupportedClaims,
        informationDensity: obsNode?.informationDensity,
        curiosityGap: obsNode?.curiosityGap,
        primaryQuestion: obsNode?.primaryQuestion,
        winningCandidateReason: obsNode?.winningCandidateReason,
        factCorrections: editNode?.factCorrections,
        sectionsExpanded: editNode?.sectionsExpanded,
        sectionsCompressed: editNode?.sectionsCompressed,
        transitionsImproved: editNode?.transitionsImproved,
        hookStrengthened: editNode?.hookStrengthened,
        insightDensity: obsNode?.insightDensity,
        insightOriginality: obsNode?.insightOriginality,
        factToInsightRatio: obsNode?.factToInsightRatio,
        insightsGenerated: obsNode?.insightsGenerated,
        insightsUsed: obsNode?.insightsUsed,
      });

      return {
        status: "completed",
        result: {
          topic: {
            title: resultState.currentTopic.title,
            domain: resultState.currentTopic.domain,
            summary: resultState.currentTopic.summary,
          },
          article: resultState.article,
          articleId: resultState.articleId,
          sessionId: resultState.articleId || `session-${Date.now()}`,
          rabbitHoles: resultState.rabbitHoles,
          tldr: resultState.tldr,
        },
      };
    } catch (err: any) {
      errorMsg = err.message || String(err);
      console.error(`❌ [Worker] Job ${jobId} failed:`, err);

      // Log failure
      await pipelineLogger.logRun({
        userId,
        topic: topic?.title,
        startTime,
        nodes: [
          {
            nodeName: "pipeline",
            durationMs: Date.now() - new Date(startTime).getTime(),
            success: false,
            error: errorMsg,
          },
        ],
          tavilySearchCount: 0,
          totalCostEstimate: 0,
          status: "failed",
          error: errorMsg,
      });

      throw err;
    } finally {
      activeAbortControllers.delete(jobId);
      await redisSub.unsubscribe(cancelChannel);
    }
  },
  { connection: redisConnection as any },
);

worker.on("failed", (job, err) => {
  if (job) {
    console.log(`Job ${job.id} failed with error ${err.message}`);
  }
});
